from handlers import client
from handlers import load
from handlers import send_coin
from handlers import registration
from handlers import message_to_admin
from handlers import add_subscription
from handlers import delete_subscription
from handlers import message_to_user
from handlers import change_name
